### ISSUE TITLE
permessage-deflate support

### ISSUE THREAD

**Issue by Kardax** [aspnet/WebSockets#140] opened 2017-01-24 16:10 UTC
`permessage-deflate` can be used to reduce the size of messages, such as the highly-compressible JSON format.  Each message can independently choose to be compressed or uncompressed, depending on the nature of its content.

Adding this feature would facilitate delivery of more data in bandwidth-constrained scenarios, such as cellular networks, without having to fall back to traditional HTTP data transfer, where compression is already supported.

It appears to be supported by the major browsers, and as an optional protocol extension, would gracefully fall back if not supported.

The spec is here: https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-13

**Comment by Tratcher** [comment] 2017-01-24 16:42
Duplicate of https://github.com/aspnet/WebSockets/issues/19

**Closed by Tratcher** 2017-01-24 16:42 UTC

**Comment by Kardax** [comment] 2017-01-24 16:44
Oops, sorry!
